alias sw='cd ~/<%= node['workspace_directory'] %>/sprout-wrap'
alias sprout='cd ~/<%= node['workspace_directory'] %>/sprout'
alias mcchef='cd ~/<%= node['workspace_directory'] %>/chef-repo'
alias dschef='cd ~/<%= node['workspace_directory'] %>/chef-config-data-science'
alias mci='cd ~/<%= node['workspace_directory'] %>/mc-intelligence'
alias poptarts='cd ~/<%= node['workspace_directory'] %>/datasci-poptarts'
alias poptartsc='cd ~/<%= node['workspace_directory'] %>/datasci-poptarts-cookbook'
alias simit='cd ~/<%= node['workspace_directory'] %>/datasci-simit && source ~/.virtualenv/simit/bin/activate'
alias simitc='cd ~/<%= node['workspace_directory'] %>/datasci-simit-cookbook'
alias contl='cd ~/<%= node['workspace_directory'] %>/datasci-continental'
alias contlc='cd ~/<%= node['workspace_directory'] %>/datasci-continental-cookbook'
alias blubber='cd ~/<%= node['workspace_directory'] %>/datasci-blubber'
alias blubberc='cd ~/<%= node['workspace_directory'] %>/datasci-blubber-cookbook'
alias rolloats='cd ~/<%= node['workspace_directory'] %>/datasci-rolled-oats'
alias mimosa='cd ~/<%= node['workspace_directory'] %>/mimosa'
alias mimosac='cd ~/<%= node['workspace_directory'] %>/mimosa-cookbook'
