include_recipe "sprout-osx-apps::skype"
include_recipe "sprout-osx-apps::hipchat"
include_recipe "sprout-osx-apps::dropbox"
include_recipe "sprout-osx-apps::chrome"
#include_recipe "pivotal_workstation::omnigraffle"
