maintainer        'Aiyesha'
license           'MIT'
description       'Uses pivotal_workstation to configure an OSX workstation for misc development'
long_description  'Uses pivotal_workstation to configure an OSX workstation for ruby, python, julia, lua development'
version           '0.1.0'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-base'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
depends           'dmg'
depends           'python'
